### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by luczeng** [ETH3D/multi-view-evaluation#1] opened 2018-02-07 13:20 UTC
Hello,

I'm trying to use your script and I get the following error : segmentation fault (core dumped)
Any idea on how to fix this ?

Thanks

**Comment by puzzlepaint** [comment] 2018-05-10 14:32
This issue needs a more detailed description, since this is a very common program error. How to reproduce it? Was this fixed by https://github.com/ETH3D/multi-view-evaluation/pull/2 ?

**Comment by luczeng** [comment] 2018-05-23 12:52
Yes it fixed it. The bug is apparently platform dependent, I had it only on 1 computer while on 2 others it worked fine. Don't know enough about alignment issues to really understand the reason though.

**Comment by puzzlepaint** [comment] 2018-05-23 13:31
Ok, thanks for the follow up. Closing this issue then.

**Closed as completed by puzzlepaint** 2018-05-23 13:31 UTC
